#costmap_common_param

footprint: [[0.813, 0.312], [0.813, -0.312], [-0.203, -0.312], [-0.203, 0.312]]
map_type: costmap

obstacle_layer:
 max_obstacle_height: 2.0
 obstacle_range: 4.0
 raytrace_range: 6.0
 track_unknown_space: true
 footprint_clearing_enabled: true
 observation_sources: scan
 scan:
  topic: scan
  observation_persistence: 0.0
  expected_update_rate: 0.0
  data_type: LaserScan
  clearing: true
  max_obstacle_height: 2.0
  min_obstacle_height: 0.1
  obstacle_range: 4.0
  raytrace_range: 6.0 
  inf_is_valid: true

inflation_layer:
 inflation_radius: 0.2
 cost_scaling_factor: 1.5

static_layer: 
 unknown_cost_value: -1
 lethal_cost_threshold: 240
 map_topic: map
 first_map_only: false
 subscribe_to_updates: false
 track_unknown_space: true
 use_maximum: false
 trinary_costmap: true
