DWAPlannerROS:
 acc_lim_x: 0.3
 acc_lim_y: 0.0
 acc_lim_th: 0.5
 max_trans_vel: 0.3
 min_trans_vel: 0.1
 max_vel_x: 0.3
 min_vel_x: -0.3
 max_vel_y: 0.0
 min_vel_y: 0.0
 max_rot_vel: 0.7
 min_rot_vel: 0.3

###############################
#Goal Tolerance Parameters
###############################
 yaw_goal_tolerance: 0.2
 xy_goal_tolerance: 0.2
 latch_xy_goal_tolerance: false

###############################
#Forward Simulation Parameters
###############################
 sim_time: 4.0
 sim_granularity: 0.1
 vx_samples: 15
 vy_samples: 0
 vth_samples: 30
 controller_frequency: 3.0

 path_distance_bias: 24.0
 goal_distance_bias: 12.0
 occdist_scale: 0.01
 forward_point_distance: 0.325
 stop_time_buffer: 0.2
 scaling_speed: 0.25
 max_scaling_factor: 0.2

 oscillation_reset_dist: 0.05
 prune_plan: true

# Debugging
 publish_traj_pc : true
 publish_cost_grid_pc: true
 global_frame_id: odom
