global_costmap:
 global_frame: map
 robot_base_frame: base_link
 transform_tolerance: 0.2
 update_frequency: 2.8
 publish_frequency: 0.0
 static_map: true 
 rolling_window: false
 width: 10
 height: 10
 resolution: 0.05
 origin_x: 0.0
 origin_y: 0.0
 plugins:
   - {name: static_layer,            type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
