GlobalPlanner: 
 allow_unknown: true
 default_tolerance: 0.3
 visualize_potential: true
 use_dijkstra: false
 use_quadratic: true
 use_grid_path: false
 old_navfn_behavior: false
 lethal_cost: 253 
 neutral_cost: 40
 cost_factor: 0.35
 publish_potential: true
 orientation_mode: 0
 orientation_window_size: 1
