local_costmap:
 global_frame: odom
 robot_base_frame: base_link
 transform_tolerance: 0.2
 update_frequency: 2.8
 publish_frequency: 0.0
 static_map: false 
 rolling_window: true
 always_send_full_costmap: false
 width: 10
 height: 10
 resolution: 0.05
 origin_x: 0.0
 origin_y: 0.0
 plugins:
   - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

