base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"
#recovery_behaviors:
 # - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery} 
  #- {name: rotate_recovery, type: rotate_recovery/RotateRecovery} 
  #- {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
controller_frequency: 3.0
planner_patience: 5.0
controller_patience: 15.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
shutdown_costmaps: false
oscillation_timeout: 3.0
oscillation_distance: 0.5
planner_frequency: 1.0
max_planning_retries: -1

#conservative_reset:
 #   reset_distance: 2.0

#aggressive_reset:
 #   reset_distance: 1.0

